export default {
  CHANGE: "CHANGE",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",

  CHAR_CREATED: 'CHAR_CREATED',
  CHAR_UPDATE: "CHAR_UPDATED",
  CHAR_DELETED: "CHAR_DELETED",

  EVENT_CREATED: 'EVENT_CREATED',
  EVENT_UPDATED: 'EVENT_UPDATED',
  EVENT_DELETED: 'EVENT_DELETED',

  COMPOSITION_CREATED: 'COMPOSITION_CREATED',
  COMPOSITION_UPDATED: 'COMPOSITION_UPDATED',
  COMPOSITION_DELETED: 'COMPOSITION_DELETED',

  NOTE_CREATED: 'NOTE_CREATED',
  NOTE_UPDATED: 'NOTE_UPDATED',
  NOTE_DELETED: 'NOTE_DELETED',

  OPTIONS_LOADED: "OPTIONS_LOADED",
  OPTIONS_CHANGED: "OPTIONS_CHANGED",

  CHANNEL_CHARACTER: 'CHARACTER',
  CHANNEL_EVENT: 'EVENT',
  CHANNEL_COMP: 'COMPOSITION',
  CHANNEL_OPTION: 'OPTION',
  CHANNEL_NOTE: 'NOTE'
};
