export default {
  CHANGE: "CHANGE",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  
  NEW_CHAR: "NEW_CHAR",
  CHAR_UPDATE: "CHAR_UPDATE",
  CHAR_DELETED: "CHAR_DELETED",
  OPTIONS_LOADED: "OPTIONS_LOADED"
};
